function rezultat = otsenit_liniyu_svyazi(pervoe_bvs, vtoroe_bvs, parametry_svyazi, shag_rascheta)

pervoe_bvs = proverit_sostoyanie_bvs(pervoe_bvs);
vtoroe_bvs = proverit_sostoyanie_bvs(vtoroe_bvs);
parametry_svyazi = proverit_parametry_svyazi(parametry_svyazi);
shag_rascheta = proverit_shag_rascheta(shag_rascheta);

rasstoyanie_m = norm(pervoe_bvs.polozhenie - vtoroe_bvs.polozhenie, 2);
effektivnaya_dalnost_m = max( ...
    rasstoyanie_m, ...
    parametry_svyazi.minimalnaya_dalnost_m);
prinimaemaya_moshchnost_vt = ...
    parametry_svyazi.moshchnost_peredatchika_vt ...
    * parametry_svyazi.usilenie_kanala ...
    / (effektivnaya_dalnost_m ^ parametry_svyazi.pokazatel_poter);
otnoshenie_signal_shum = prinimaemaya_moshchnost_vt ...
    / parametry_svyazi.moshchnost_shuma_vt;

uslovie_rabotosposobnosti = pervoe_bvs.rabotosposoben && vtoroe_bvs.rabotosposoben;
uslovie_dalnosti = rasstoyanie_m <= parametry_svyazi.maksimalnaya_dalnost_m;
uslovie_poroga = otnoshenie_signal_shum ...
    >= parametry_svyazi.porog_otnosheniya_signal_shum;
est_liniya = uslovie_rabotosposobnosti && uslovie_dalnosti && uslovie_poroga;

if est_liniya
    propusknaya_sposobnost_bit_s = ...
        parametry_svyazi.polosa_chastot_gts * log2(1 + otnoshenie_signal_shum);
    ocenochnoe_vremya_sohraneniya_svyazi_s = raschet_vremeni_sohraneniya( ...
        pervoe_bvs, vtoroe_bvs, rasstoyanie_m, parametry_svyazi, shag_rascheta);
    energeticheskaya_stoimost_dzh_na_bit = ...
        parametry_svyazi.moshchnost_peredatchika_vt ...
        / max(propusknaya_sposobnost_bit_s, eps);
    pokazateli_linii = struct( ...
        'propusknaya_sposobnost_bit_s', propusknaya_sposobnost_bit_s, ...
        'ocenochnoe_vremya_sohraneniya_svyazi_s', ocenochnoe_vremya_sohraneniya_svyazi_s, ...
        'energeticheskaya_stoimost_dzh_na_bit', energeticheskaya_stoimost_dzh_na_bit);
    poleznost_linii = raschet_poleznosti( ...
        pokazateli_linii, ...
        parametry_svyazi, ...
        shag_rascheta);
else
    propusknaya_sposobnost_bit_s = 0;
    ocenochnoe_vremya_sohraneniya_svyazi_s = 0;
    energeticheskaya_stoimost_dzh_na_bit = 0;
    poleznost_linii = 0;
end

rezultat = struct();
rezultat.est_liniya = logical(est_liniya);
rezultat.rasstoyanie_m = double(rasstoyanie_m);
rezultat.otnoshenie_signal_shum = double(otnoshenie_signal_shum);
rezultat.propusknaya_sposobnost_bit_s = double(propusknaya_sposobnost_bit_s);
rezultat.ocenochnoe_vremya_sohraneniya_svyazi_s = ...
    double(ocenochnoe_vremya_sohraneniya_svyazi_s);
rezultat.energeticheskaya_stoimost_dzh_na_bit = ...
    double(energeticheskaya_stoimost_dzh_na_bit);
rezultat.poleznost_linii = double(poleznost_linii);
end

function shag_rascheta = proverit_shag_rascheta(shag_rascheta)
if ~isnumeric(shag_rascheta) || ~isscalar(shag_rascheta) || ~isfinite(shag_rascheta)
    error('%s', 'Шаг расчета связи должен быть конечным числом.');
end

shag_rascheta = double(shag_rascheta);
if shag_rascheta <= 0
    error('%s', 'Шаг расчета связи должен быть положительным.');
end
end

function ocenochnoe_vremya_sohraneniya_svyazi_s = raschet_vremeni_sohraneniya(pervoe_bvs, vtoroe_bvs, rasstoyanie_m, parametry_svyazi, shag_rascheta)

otnositelnaya_skorost = vtoroe_bvs.skorost - pervoe_bvs.skorost;
if rasstoyanie_m > 0
    napravlenie = (vtoroe_bvs.polozhenie - pervoe_bvs.polozhenie) / rasstoyanie_m;
    skorost_raskhozhdeniya = abs(dot(otnositelnaya_skorost, napravlenie));
else
    skorost_raskhozhdeniya = norm(otnositelnaya_skorost, 2);
end

bazovaya_skorost_m_s = parametry_svyazi.minimalnaya_dalnost_m / shag_rascheta;
effektivnaya_skorost_m_s = max(skorost_raskhozhdeniya, bazovaya_skorost_m_s);
zapas_dalnosti_m = max( ...
    parametry_svyazi.maksimalnaya_dalnost_m - rasstoyanie_m, ...
    0);
ocenochnoe_vremya_sohraneniya_svyazi_s = ...
    shag_rascheta + zapas_dalnosti_m / effektivnaya_skorost_m_s;
end

function poleznost_linii = raschet_poleznosti(pokazateli_linii, parametry_svyazi, shag_rascheta)

maksimalnoe_otnoshenie = ...
    parametry_svyazi.moshchnost_peredatchika_vt ...
    * parametry_svyazi.usilenie_kanala ...
    / (parametry_svyazi.minimalnaya_dalnost_m ^ parametry_svyazi.pokazatel_poter) ...
    / parametry_svyazi.moshchnost_shuma_vt;
opornaya_propusknaya_sposobnost = ...
    parametry_svyazi.polosa_chastot_gts * log2(1 + maksimalnoe_otnoshenie);
normalizovannaya_propusknaya_sposobnost = min( ...
    pokazateli_linii.propusknaya_sposobnost_bit_s / max(opornaya_propusknaya_sposobnost, eps), ...
    1);

opornoe_vremya_svyazi = shag_rascheta ...
    + (parametry_svyazi.maksimalnaya_dalnost_m ...
    - parametry_svyazi.minimalnaya_dalnost_m) ...
    / (parametry_svyazi.minimalnaya_dalnost_m / shag_rascheta);
normalizovannaya_dlitelnost = min( ...
    pokazateli_linii.ocenochnoe_vremya_sohraneniya_svyazi_s / max(opornoe_vremya_svyazi, eps), ...
    1);

porogovaya_propusknaya_sposobnost = ...
    parametry_svyazi.polosa_chastot_gts ...
    * log2(1 + parametry_svyazi.porog_otnosheniya_signal_shum);
opornaya_energeticheskaya_stoimost = ...
    parametry_svyazi.moshchnost_peredatchika_vt ...
    / max(porogovaya_propusknaya_sposobnost, eps);
energeticheskaya_ocenka = 1 - min( ...
    pokazateli_linii.energeticheskaya_stoimost_dzh_na_bit ...
    / max(opornaya_energeticheskaya_stoimost, eps), ...
    1);

summa_vesov = parametry_svyazi.ves_propusknoi_sposobnosti ...
    + parametry_svyazi.ves_dlitelnosti_svyazi ...
    + parametry_svyazi.ves_energeticheskoi_stoimosti;
if summa_vesov <= 0
    error('%s', 'Сумма весов полезности линии связи должна быть положительной.');
end

poleznost_linii = ( ...
    parametry_svyazi.ves_propusknoi_sposobnosti ...
    * normalizovannaya_propusknaya_sposobnost ...
    + parametry_svyazi.ves_dlitelnosti_svyazi ...
    * normalizovannaya_dlitelnost ...
    + parametry_svyazi.ves_energeticheskoi_stoimosti ...
    * energeticheskaya_ocenka) / summa_vesov;

poleznost_linii = min(max(poleznost_linii, 0), 1);
end
