function parametry = parametry_svyazi_po_umolchaniyu()
parametry = struct( ...
    'moshchnost_peredatchika_vt', 2.0, ...
    'usilenie_kanala', 1.0, ...
    'pokazatel_poter', 2.2, ...
    'moshchnost_shuma_vt', 1e-9, ...
    'polosa_chastot_gts', 2e6, ...
    'porog_otnosheniya_signal_shum', 3.0, ...
    'minimalnaya_dalnost_m', 1.0, ...
    'maksimalnaya_dalnost_m', 120.0, ...
    'razmer_soobshcheniya_bit', 4096.0, ...
    'ves_propusknoi_sposobnosti', 0.45, ...
    'ves_dlitelnosti_svyazi', 0.35, ...
    'ves_energeticheskoi_stoimosti', 0.20);

parametry = proverit_parametry_svyazi(parametry);
end
