function parametry = proverit_parametry_svyazi(parametry)
if nargin < 1 || ~isstruct(parametry)
    error('%s', 'Для проверки параметров связи требуется структура.');
end

obyazatelnye_polya = {
    'moshchnost_peredatchika_vt'
    'usilenie_kanala'
    'pokazatel_poter'
    'moshchnost_shuma_vt'
    'polosa_chastot_gts'
    'porog_otnosheniya_signal_shum'
    'minimalnaya_dalnost_m'
    'maksimalnaya_dalnost_m'
    'razmer_soobshcheniya_bit'
    'ves_propusknoi_sposobnosti'
    'ves_dlitelnosti_svyazi'
    'ves_energeticheskoi_stoimosti'
    };

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(parametry, imya_polya)
        error('%s', sprintf( ...
            'В параметрах связи отсутствует обязательное поле %s.', ...
            imya_polya));
    end
end

parametry.moshchnost_peredatchika_vt = proverit_polozhitelnoe_chislo( ...
    parametry.moshchnost_peredatchika_vt, ...
    'moshchnost_peredatchika_vt');
parametry.usilenie_kanala = proverit_polozhitelnoe_chislo( ...
    parametry.usilenie_kanala, ...
    'usilenie_kanala');
parametry.pokazatel_poter = proverit_polozhitelnoe_chislo( ...
    parametry.pokazatel_poter, ...
    'pokazatel_poter');
parametry.moshchnost_shuma_vt = proverit_polozhitelnoe_chislo( ...
    parametry.moshchnost_shuma_vt, ...
    'moshchnost_shuma_vt');
parametry.polosa_chastot_gts = proverit_polozhitelnoe_chislo( ...
    parametry.polosa_chastot_gts, ...
    'polosa_chastot_gts');
parametry.porog_otnosheniya_signal_shum = proverit_polozhitelnoe_chislo( ...
    parametry.porog_otnosheniya_signal_shum, ...
    'porog_otnosheniya_signal_shum');
parametry.minimalnaya_dalnost_m = proverit_polozhitelnoe_chislo( ...
    parametry.minimalnaya_dalnost_m, ...
    'minimalnaya_dalnost_m');
parametry.maksimalnaya_dalnost_m = proverit_polozhitelnoe_chislo( ...
    parametry.maksimalnaya_dalnost_m, ...
    'maksimalnaya_dalnost_m');
parametry.razmer_soobshcheniya_bit = proverit_polozhitelnoe_chislo( ...
    parametry.razmer_soobshcheniya_bit, ...
    'razmer_soobshcheniya_bit');
parametry.ves_propusknoi_sposobnosti = proverit_neotricatelnoe_chislo( ...
    parametry.ves_propusknoi_sposobnosti, ...
    'ves_propusknoi_sposobnosti');
parametry.ves_dlitelnosti_svyazi = proverit_neotricatelnoe_chislo( ...
    parametry.ves_dlitelnosti_svyazi, ...
    'ves_dlitelnosti_svyazi');
parametry.ves_energeticheskoi_stoimosti = proverit_neotricatelnoe_chislo( ...
    parametry.ves_energeticheskoi_stoimosti, ...
    'ves_energeticheskoi_stoimosti');

if parametry.maksimalnaya_dalnost_m <= parametry.minimalnaya_dalnost_m
    error('%s', [ ...
        'Максимальная дальность связи должна быть больше минимальной ' ...
        'дальности.' ...
        ]);
end

summa_vesov = parametry.ves_propusknoi_sposobnosti ...
    + parametry.ves_dlitelnosti_svyazi ...
    + parametry.ves_energeticheskoi_stoimosti;
if summa_vesov <= 0
    error('%s', 'Сумма весов полезности линии связи должна быть положительной.');
end
end

function znachenie = proverit_polozhitelnoe_chislo(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie <= 0
    error('%s', sprintf( ...
        'Поле %s должно быть положительным.', ...
        imya_polya));
end
end

function znachenie = proverit_neotricatelnoe_chislo(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie < 0
    error('%s', sprintf( ...
        'Поле %s не может быть отрицательным.', ...
        imya_polya));
end
end
