function svodka_dopustimosti = otsenit_dopustimost_resursov_serii(rezultat_resursov_serii, parametry_resursov)
if nargin < 1
    error('%s', [ ...
        'Для оценки ресурсной допустимости серии требуется ресурсная ' ...
        'сводка серии.' ...
        ]);
end

rezultat_resursov_serii = proverit_rezultat_resursov_serii(rezultat_resursov_serii);
parametry_resursov = opredelit_parametry_resursov( ...
    rezultat_resursov_serii, ...
    nargin, ...
    parametry_resursov);

chislo_variantov = numel(rezultat_resursov_serii.resursy_po_variantam);
dopustimost_po_variantam = repmat(struct( ...
    'itog_dopustim', true, ...
    'energia_dopustima', true, ...
    'vychislitelnaya_nagruzka_dopustima', true, ...
    'ocheredi_dopustimy', true, ...
    'nagruzka_golovnogo_bvs_dopustima', true, ...
    'nagruzka_svyazi_dopustima', true, ...
    'narusheniya', {{}}, ...
    'opisanie_narushenii', '', ...
    'fakticheskaya_dolya_bvs_s_dostatochnoi_energiey', 0, ...
    'minimalnyi_ostatok_energii_dzh', 0, ...
    'srednyaya_vychislitelnaya_nagruzka', 0, ...
    'maksimalnaya_vychislitelnaya_nagruzka', 0, ...
    'srednyaya_zanyatost_ocheredi', 0, ...
    'maksimalnaya_zanyatost_ocheredi', 0, ...
    'srednyaya_nagruzka_svyazi', 0, ...
    'maksimalnaya_nagruzka_svyazi', 0, ...
    'maksimalnaya_nagruzka_golovnogo_bvs', 0), ...
    1, chislo_variantov);

itog_dopustim = false(chislo_variantov, 1);
energia_dopustima = false(chislo_variantov, 1);
vychislitelnaya_nagruzka_dopustima = false(chislo_variantov, 1);
ocheredi_dopustimy = false(chislo_variantov, 1);
nagruzka_golovnogo_bvs_dopustima = false(chislo_variantov, 1);
nagruzka_svyazi_dopustima = false(chislo_variantov, 1);
chislo_narushenii = zeros(chislo_variantov, 1);
opisaniya_narushenii_po_variantam = cell(chislo_variantov, 1);

for nomer_varianta = 1:chislo_variantov
    dopustimost = otsenit_dopustimost_resursov_opyta( ...
        rezultat_resursov_serii.resursy_po_variantam(nomer_varianta), ...
        parametry_resursov);
    dopustimost_po_variantam(nomer_varianta) = dopustimost;
    itog_dopustim(nomer_varianta) = dopustimost.itog_dopustim;
    energia_dopustima(nomer_varianta) = dopustimost.energia_dopustima;
    vychislitelnaya_nagruzka_dopustima(nomer_varianta) = ...
        dopustimost.vychislitelnaya_nagruzka_dopustima;
    ocheredi_dopustimy(nomer_varianta) = dopustimost.ocheredi_dopustimy;
    nagruzka_golovnogo_bvs_dopustima(nomer_varianta) = ...
        dopustimost.nagruzka_golovnogo_bvs_dopustima;
    nagruzka_svyazi_dopustima(nomer_varianta) = ...
        dopustimost.nagruzka_svyazi_dopustima;
    chislo_narushenii(nomer_varianta) = numel(dopustimost.narusheniya);
    opisaniya_narushenii_po_variantam{nomer_varianta} = ...
        dopustimost.opisanie_narushenii;
end

tablica_resursov = rezultat_resursov_serii.tablica_resursov;
if height(tablica_resursov) ~= chislo_variantov
    error('%s', [ ...
        'Число строк таблицы ресурсов не совпадает с числом вариантов ' ...
        'ресурсной серии.' ...
        ]);
end

tablica_resursov.itog_dopustim = itog_dopustim;
tablica_resursov.energia_dopustima = energia_dopustima;
tablica_resursov.vychislitelnaya_nagruzka_dopustima = ...
    vychislitelnaya_nagruzka_dopustima;
tablica_resursov.ocheredi_dopustimy = ocheredi_dopustimy;
tablica_resursov.nagruzka_golovnogo_bvs_dopustima = ...
    nagruzka_golovnogo_bvs_dopustima;
tablica_resursov.nagruzka_svyazi_dopustima = nagruzka_svyazi_dopustima;
tablica_resursov.chislo_narushenii = chislo_narushenii;

svodka_dopustimosti = struct();
svodka_dopustimosti.tablica_resursov = tablica_resursov;
svodka_dopustimosti.dopustimost_po_variantam = dopustimost_po_variantam;
svodka_dopustimosti.opisaniya_narushenii_po_variantam = ...
    opisaniya_narushenii_po_variantam;
svodka_dopustimosti.chislo_dopustimyh_variantov = sum(itog_dopustim);
svodka_dopustimosti.chislo_nedopustimyh_variantov = sum(~itog_dopustim);
svodka_dopustimosti.osnovnye_prichiny_narushenii = ...
    sobrat_unikalnye_prichiny(dopustimost_po_variantam);
svodka_dopustimosti.primechanie = [ ...
    'Ресурсная допустимость серии рассчитана поверх уже полученных ' ...
    'ресурсных показателей без изменения опытов и их результатов.' ...
    ];
end

function rezultat_resursov_serii = proverit_rezultat_resursov_serii(rezultat_resursov_serii)
if ~isstruct(rezultat_resursov_serii) ...
        || ~isfield(rezultat_resursov_serii, 'tablica_resursov') ...
        || ~isfield(rezultat_resursov_serii, 'resursy_po_variantam')
    error('%s', [ ...
        'Ресурсная сводка серии должна содержать таблицу ресурсов и ' ...
        'список ресурсов по вариантам.' ...
        ]);
end
end

function parametry_resursov = opredelit_parametry_resursov(rezultat_resursov_serii, chislo_vhodnyh_argumentov, parametry_resursov)
if chislo_vhodnyh_argumentov < 2 || isempty(parametry_resursov)
    if numel(rezultat_resursov_serii.resursy_po_variantam) < 1 ...
            || ~isfield(rezultat_resursov_serii.resursy_po_variantam(1), ...
            'parametry_resursov')
        error('%s', [ ...
            'Для оценки допустимости серии требуется передать параметры ' ...
            'ресурсов или сохранить их в ресурсах вариантов.' ...
            ]);
    end

    parametry_resursov = ...
        rezultat_resursov_serii.resursy_po_variantam(1).parametry_resursov;
end

parametry_resursov = proverit_parametry_resursov(parametry_resursov);
end

function osnovnye_prichiny = sobrat_unikalnye_prichiny(dopustimost_po_variantam)
osnovnye_prichiny = {};
for nomer_varianta = 1:numel(dopustimost_po_variantam)
    narusheniya = dopustimost_po_variantam(nomer_varianta).narusheniya;
    for nomer_narusheniya = 1:numel(narusheniya)
        tekushchaya_prichina = narusheniya{nomer_narusheniya};
        if ~any(strcmp(osnovnye_prichiny, tekushchaya_prichina))
            osnovnye_prichiny{end + 1} = tekushchaya_prichina; %#ok<AGROW>
        end
    end
end
end
