function dopustimost = otsenit_dopustimost_resursov_opyta(rezultat_resursov, parametry_resursov)
if nargin < 1
    error('%s', [ ...
        'Для оценки ресурсной допустимости опыта требуется структура ' ...
        'ресурсной сводки.' ...
        ]);
end

rezultat_resursov = proverit_rezultat_resursov(rezultat_resursov);
parametry_resursov = opredelit_parametry_resursov( ...
    rezultat_resursov, ...
    nargin, ...
    parametry_resursov);

minimalnyi_ostatok_energii = min(rezultat_resursov.energiya_ostatok_itog);
dolya_bvs_s_dostatochnoi_energiey = double( ...
    rezultat_resursov.dolya_bvs_s_dostatochnoi_energiey);
srednyaya_vychislitelnaya_nagruzka = mean( ...
    rezultat_resursov.vychislitelnaya_nagruzka_po_vremeni, ...
    'all');
maksimalnaya_vychislitelnaya_nagruzka = max( ...
    rezultat_resursov.vychislitelnaya_nagruzka_po_vremeni, ...
    [], ...
    'all');
srednyaya_zanyatost_ocheredi = mean( ...
    rezultat_resursov.zanyatost_ocheredei.srednyaya_zanyatost);
maksimalnaya_zanyatost_ocheredi = max( ...
    rezultat_resursov.zanyatost_ocheredei.maksimalnaya_zanyatost);
maksimalnaya_nagruzka_golovnogo_bvs = double( ...
    rezultat_resursov.maksimalnaya_nagruzka_golovnogo_bvs);
[srednyaya_nagruzka_svyazi, maksimalnaya_nagruzka_svyazi] = ...
    sobrat_nagruzku_svyazi(rezultat_resursov);

energia_dopustima = ...
    dolya_bvs_s_dostatochnoi_energiey >= ...
    parametry_resursov.minimalnaya_dolya_bvs_s_dostatochnoi_energiey ...
    && minimalnyi_ostatok_energii >= ...
    parametry_resursov.minimalnyi_dopustimyi_ostatok_energii_dzh;
vychislitelnaya_nagruzka_dopustima = ...
    srednyaya_vychislitelnaya_nagruzka <= ...
    parametry_resursov.maksimalnaya_srednyaya_vychislitelnaya_nagruzka ...
    && maksimalnaya_vychislitelnaya_nagruzka <= ...
    parametry_resursov.maksimalnaya_maksimalnaya_vychislitelnaya_nagruzka;
ocheredi_dopustimy = ...
    srednyaya_zanyatost_ocheredi <= ...
    parametry_resursov.maksimalnaya_srednyaya_zanyatost_ocheredi ...
    && maksimalnaya_zanyatost_ocheredi <= ...
    parametry_resursov.maksimalnaya_maksimalnaya_zanyatost_ocheredi;
nagruzka_golovnogo_bvs_dopustima = ...
    maksimalnaya_nagruzka_golovnogo_bvs <= ...
    parametry_resursov.maksimalnaya_dolya_nagruzki_golovnogo_bvs;
nagruzka_svyazi_dopustima = ...
    maksimalnaya_nagruzka_svyazi <= ...
    parametry_resursov.maksimalnaya_nagruzka_linii_svyazi;

narusheniya = {};
narusheniya = dobavit_narushenie_energii( ...
    narusheniya, ...
    energia_dopustima, ...
    dolya_bvs_s_dostatochnoi_energiey, ...
    minimalnyi_ostatok_energii, ...
    parametry_resursov);
narusheniya = dobavit_narushenie_vychislenii( ...
    narusheniya, ...
    vychislitelnaya_nagruzka_dopustima, ...
    srednyaya_vychislitelnaya_nagruzka, ...
    maksimalnaya_vychislitelnaya_nagruzka, ...
    parametry_resursov);
narusheniya = dobavit_narushenie_ocheredei( ...
    narusheniya, ...
    ocheredi_dopustimy, ...
    srednyaya_zanyatost_ocheredi, ...
    maksimalnaya_zanyatost_ocheredi, ...
    parametry_resursov);
narusheniya = dobavit_narushenie_golovnogo_bvs( ...
    narusheniya, ...
    nagruzka_golovnogo_bvs_dopustima, ...
    maksimalnaya_nagruzka_golovnogo_bvs, ...
    parametry_resursov);
narusheniya = dobavit_narushenie_svyazi( ...
    narusheniya, ...
    nagruzka_svyazi_dopustima, ...
    maksimalnaya_nagruzka_svyazi, ...
    parametry_resursov);

itog_dopustim = energia_dopustima ...
    && vychislitelnaya_nagruzka_dopustima ...
    && ocheredi_dopustimy ...
    && nagruzka_golovnogo_bvs_dopustima ...
    && nagruzka_svyazi_dopustima;

dopustimost = struct();
dopustimost.itog_dopustim = itog_dopustim;
dopustimost.energia_dopustima = energia_dopustima;
dopustimost.vychislitelnaya_nagruzka_dopustima = ...
    vychislitelnaya_nagruzka_dopustima;
dopustimost.ocheredi_dopustimy = ocheredi_dopustimy;
dopustimost.nagruzka_golovnogo_bvs_dopustima = ...
    nagruzka_golovnogo_bvs_dopustima;
dopustimost.nagruzka_svyazi_dopustima = nagruzka_svyazi_dopustima;
dopustimost.narusheniya = narusheniya;
dopustimost.opisanie_narushenii = sobrat_opisanie_narushenii(narusheniya);
dopustimost.fakticheskaya_dolya_bvs_s_dostatochnoi_energiey = ...
    dolya_bvs_s_dostatochnoi_energiey;
dopustimost.minimalnyi_ostatok_energii_dzh = minimalnyi_ostatok_energii;
dopustimost.srednyaya_vychislitelnaya_nagruzka = ...
    srednyaya_vychislitelnaya_nagruzka;
dopustimost.maksimalnaya_vychislitelnaya_nagruzka = ...
    maksimalnaya_vychislitelnaya_nagruzka;
dopustimost.srednyaya_zanyatost_ocheredi = srednyaya_zanyatost_ocheredi;
dopustimost.maksimalnaya_zanyatost_ocheredi = ...
    maksimalnaya_zanyatost_ocheredi;
dopustimost.srednyaya_nagruzka_svyazi = srednyaya_nagruzka_svyazi;
dopustimost.maksimalnaya_nagruzka_svyazi = maksimalnaya_nagruzka_svyazi;
dopustimost.maksimalnaya_nagruzka_golovnogo_bvs = ...
    maksimalnaya_nagruzka_golovnogo_bvs;
end

function rezultat_resursov = proverit_rezultat_resursov(rezultat_resursov)
obyazatelnye_polya = {
    'energiya_ostatok_itog'
    'vychislitelnaya_nagruzka_po_vremeni'
    'zanyatost_ocheredei'
    'nagruzka_golovnyh_bvs'
    'dolya_bvs_s_dostatochnoi_energiey'
    'maksimalnaya_nagruzka_golovnogo_bvs'
    };

if ~isstruct(rezultat_resursov)
    error('%s', ...
        'Результат ресурсов для оценки допустимости должен быть структурой.');
end

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(rezultat_resursov, imya_polya)
        error('%s', sprintf( ...
            'В результате ресурсов отсутствует поле %s.', ...
            imya_polya));
    end
end
end

function parametry_resursov = opredelit_parametry_resursov(rezultat_resursov, chislo_vhodnyh_argumentov, parametry_resursov)
if chislo_vhodnyh_argumentov < 2 || isempty(parametry_resursov)
    if ~isfield(rezultat_resursov, 'parametry_resursov')
        error('%s', [ ...
            'Для оценки допустимости требуется передать параметры ресурсов ' ...
            'или сохранить их в структуре результата.' ...
            ]);
    end

    parametry_resursov = rezultat_resursov.parametry_resursov;
end

parametry_resursov = proverit_parametry_resursov(parametry_resursov);
end

function [srednyaya_nagruzka_svyazi, maksimalnaya_nagruzka_svyazi] = sobrat_nagruzku_svyazi(rezultat_resursov)
if ~isfield(rezultat_resursov, 'nagruzka_svyazi_po_vremeni') ...
        || isempty(rezultat_resursov.nagruzka_svyazi_po_vremeni)
    srednyaya_nagruzka_svyazi = 0;
    maksimalnaya_nagruzka_svyazi = 0;
    return
end

srednyaya_nagruzka_svyazi = mean( ...
    rezultat_resursov.nagruzka_svyazi_po_vremeni, ...
    'all');
maksimalnaya_nagruzka_svyazi = max( ...
    rezultat_resursov.nagruzka_svyazi_po_vremeni, ...
    [], ...
    'all');
end

function narusheniya = dobavit_narushenie_energii(narusheniya, energia_dopustima, dolya_bvs, minimalnyi_ostatok, parametry_resursov)
if energia_dopustima
    return
end

if dolya_bvs < parametry_resursov.minimalnaya_dolya_bvs_s_dostatochnoi_energiey
    narusheniya{end + 1} = sprintf([ ...
        'Доля БВС с достаточной энергией %.4f ниже порога %.4f.' ...
        ], ...
        dolya_bvs, ...
        parametry_resursov.minimalnaya_dolya_bvs_s_dostatochnoi_energiey); %#ok<AGROW>
end

if minimalnyi_ostatok < parametry_resursov.minimalnyi_dopustimyi_ostatok_energii_dzh
    narusheniya{end + 1} = sprintf([ ...
        'Минимальный остаток энергии %.4f Дж ниже порога %.4f Дж.' ...
        ], ...
        minimalnyi_ostatok, ...
        parametry_resursov.minimalnyi_dopustimyi_ostatok_energii_dzh); %#ok<AGROW>
end
end

function narusheniya = dobavit_narushenie_vychislenii(narusheniya, dopustimo, srednee_znachenie, maksimalnoe_znachenie, parametry_resursov)
if dopustimo
    return
end

if srednee_znachenie ...
        > parametry_resursov.maksimalnaya_srednyaya_vychislitelnaya_nagruzka
    narusheniya{end + 1} = sprintf([ ...
        'Средняя вычислительная нагрузка %.4f превышает порог %.4f.' ...
        ], ...
        srednee_znachenie, ...
        parametry_resursov.maksimalnaya_srednyaya_vychislitelnaya_nagruzka); %#ok<AGROW>
end

if maksimalnoe_znachenie ...
        > parametry_resursov.maksimalnaya_maksimalnaya_vychislitelnaya_nagruzka
    narusheniya{end + 1} = sprintf([ ...
        'Максимальная вычислительная нагрузка %.4f превышает порог %.4f.' ...
        ], ...
        maksimalnoe_znachenie, ...
        parametry_resursov.maksimalnaya_maksimalnaya_vychislitelnaya_nagruzka); %#ok<AGROW>
end
end

function narusheniya = dobavit_narushenie_ocheredei(narusheniya, dopustimo, srednee_znachenie, maksimalnoe_znachenie, parametry_resursov)
if dopustimo
    return
end

if srednee_znachenie > parametry_resursov.maksimalnaya_srednyaya_zanyatost_ocheredi
    narusheniya{end + 1} = sprintf([ ...
        'Средняя занятость очереди %.4f превышает порог %.4f.' ...
        ], ...
        srednee_znachenie, ...
        parametry_resursov.maksimalnaya_srednyaya_zanyatost_ocheredi); %#ok<AGROW>
end

if maksimalnoe_znachenie ...
        > parametry_resursov.maksimalnaya_maksimalnaya_zanyatost_ocheredi
    narusheniya{end + 1} = sprintf([ ...
        'Максимальная занятость очереди %.4f превышает порог %.4f.' ...
        ], ...
        maksimalnoe_znachenie, ...
        parametry_resursov.maksimalnaya_maksimalnaya_zanyatost_ocheredi); %#ok<AGROW>
end
end

function narusheniya = dobavit_narushenie_golovnogo_bvs(narusheniya, dopustimo, maksimalnoe_znachenie, parametry_resursov)
if dopustimo
    return
end

narusheniya{end + 1} = sprintf([ ...
    'Нагрузка головного БВС %.4f превышает порог %.4f.' ...
    ], ...
    maksimalnoe_znachenie, ...
    parametry_resursov.maksimalnaya_dolya_nagruzki_golovnogo_bvs);
end

function narusheniya = dobavit_narushenie_svyazi(narusheniya, dopustimo, maksimalnoe_znachenie, parametry_resursov)
if dopustimo
    return
end

narusheniya{end + 1} = sprintf([ ...
    'Нагрузка линии связи %.4f превышает порог %.4f.' ...
    ], ...
    maksimalnoe_znachenie, ...
    parametry_resursov.maksimalnaya_nagruzka_linii_svyazi);
end

function opisanie = sobrat_opisanie_narushenii(narusheniya)
if isempty(narusheniya)
    opisanie = 'Нарушений ресурсной допустимости не обнаружено.';
else
    opisanie = strjoin(narusheniya, ' ');
end
end
