function parametry = parametry_resursov_po_umolchaniyu()
parametry = struct( ...
    'energiya_start_dzh', 1800.0, ...
    'energiya_minimalnaya_dzh', 180.0, ...
    'zatraty_dvizheniya_dzh_na_m', 0.08, ...
    'zatraty_priema_dzh_na_bit', 1e-6, ...
    'zatraty_peredachi_dzh_na_bit', 2e-6, ...
    'zatraty_obrabotki_dzh_na_operaciyu', 5e-5, ...
    'vychislitelnaya_moshchnost_operacii_v_s', 2e5, ...
    'nagruzka_obrabotki_soobshcheniya_operacii', 250.0, ...
    'maksimalnaya_dolya_zanyatosti_ocheredi', 0.85, ...
    'maksimalnaya_dolya_nagruzki_golovnogo_bvs', 0.90, ...
    'minimalnaya_dolya_bvs_s_dostatochnoi_energiey', 0.80, ...
    'minimalnyi_dopustimyi_ostatok_energii_dzh', 180.0, ...
    'maksimalnaya_srednyaya_vychislitelnaya_nagruzka', 0.75, ...
    'maksimalnaya_maksimalnaya_vychislitelnaya_nagruzka', 0.95, ...
    'maksimalnaya_srednyaya_zanyatost_ocheredi', 0.60, ...
    'maksimalnaya_maksimalnaya_zanyatost_ocheredi', 0.85, ...
    'maksimalnaya_nagruzka_linii_svyazi', 0.95, ...
    'uchityvat_ogranichenie_energii', true, ...
    'uchityvat_ogranichenie_ocheredi', true);

parametry = proverit_parametry_resursov(parametry);
end
