function parametry = proverit_parametry_resursov(parametry)
if nargin < 1 || ~isstruct(parametry)
    error('%s', ...
        'Для проверки параметров ресурсов требуется структура параметров.');
end

obyazatelnye_polya = {
    'energiya_start_dzh'
    'energiya_minimalnaya_dzh'
    'zatraty_dvizheniya_dzh_na_m'
    'zatraty_priema_dzh_na_bit'
    'zatraty_peredachi_dzh_na_bit'
    'zatraty_obrabotki_dzh_na_operaciyu'
    'vychislitelnaya_moshchnost_operacii_v_s'
    'nagruzka_obrabotki_soobshcheniya_operacii'
    'maksimalnaya_dolya_zanyatosti_ocheredi'
    'maksimalnaya_dolya_nagruzki_golovnogo_bvs'
    'uchityvat_ogranichenie_energii'
    'uchityvat_ogranichenie_ocheredi'
    };

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(parametry, imya_polya)
        error('%s', sprintf( ...
            'В параметрах ресурсов отсутствует поле %s.', ...
            imya_polya));
    end
end

parametry.energiya_start_dzh = proverit_polozhitelnoe_chislo( ...
    parametry.energiya_start_dzh, ...
    'energiya_start_dzh');
parametry.energiya_minimalnaya_dzh = proverit_neotricatelnoe_chislo( ...
    parametry.energiya_minimalnaya_dzh, ...
    'energiya_minimalnaya_dzh');
parametry.zatraty_dvizheniya_dzh_na_m = proverit_neotricatelnoe_chislo( ...
    parametry.zatraty_dvizheniya_dzh_na_m, ...
    'zatraty_dvizheniya_dzh_na_m');
parametry.zatraty_priema_dzh_na_bit = proverit_neotricatelnoe_chislo( ...
    parametry.zatraty_priema_dzh_na_bit, ...
    'zatraty_priema_dzh_na_bit');
parametry.zatraty_peredachi_dzh_na_bit = proverit_neotricatelnoe_chislo( ...
    parametry.zatraty_peredachi_dzh_na_bit, ...
    'zatraty_peredachi_dzh_na_bit');
parametry.zatraty_obrabotki_dzh_na_operaciyu = ...
    proverit_neotricatelnoe_chislo( ...
    parametry.zatraty_obrabotki_dzh_na_operaciyu, ...
    'zatraty_obrabotki_dzh_na_operaciyu');
parametry.vychislitelnaya_moshchnost_operacii_v_s = ...
    proverit_polozhitelnoe_chislo( ...
    parametry.vychislitelnaya_moshchnost_operacii_v_s, ...
    'vychislitelnaya_moshchnost_operacii_v_s');
parametry.nagruzka_obrabotki_soobshcheniya_operacii = ...
    proverit_neotricatelnoe_chislo( ...
    parametry.nagruzka_obrabotki_soobshcheniya_operacii, ...
    'nagruzka_obrabotki_soobshcheniya_operacii');
parametry.maksimalnaya_dolya_zanyatosti_ocheredi = proverit_dolyu( ...
    parametry.maksimalnaya_dolya_zanyatosti_ocheredi, ...
    'maksimalnaya_dolya_zanyatosti_ocheredi');
parametry.maksimalnaya_dolya_nagruzki_golovnogo_bvs = proverit_dolyu( ...
    parametry.maksimalnaya_dolya_nagruzki_golovnogo_bvs, ...
    'maksimalnaya_dolya_nagruzki_golovnogo_bvs');

parametry.uchityvat_ogranichenie_energii = proverit_logicheskoe_znachenie( ...
    parametry.uchityvat_ogranichenie_energii, ...
    'uchityvat_ogranichenie_energii');
parametry.uchityvat_ogranichenie_ocheredi = proverit_logicheskoe_znachenie( ...
    parametry.uchityvat_ogranichenie_ocheredi, ...
    'uchityvat_ogranichenie_ocheredi');

if parametry.energiya_minimalnaya_dzh > parametry.energiya_start_dzh
    error('%s', [ ...
        'Минимально допустимый остаток энергии не может быть больше ' ...
        'начальной энергии.' ...
        ]);
end
end

function znachenie = proverit_polozhitelnoe_chislo(znachenie, imya_polya)
znachenie = proverit_konechnoe_chislo(znachenie, imya_polya);
if znachenie <= 0
    error('%s', sprintf( ...
        'Параметр %s должен быть положительным числом.', ...
        imya_polya));
end
end

function znachenie = proverit_neotricatelnoe_chislo(znachenie, imya_polya)
znachenie = proverit_konechnoe_chislo(znachenie, imya_polya);
if znachenie < 0
    error('%s', sprintf( ...
        'Параметр %s не должен быть отрицательным.', ...
        imya_polya));
end
end

function znachenie = proverit_dolyu(znachenie, imya_polya)
znachenie = proverit_konechnoe_chislo(znachenie, imya_polya);
if znachenie < 0 || znachenie > 1
    error('%s', sprintf( ...
        'Параметр %s должен находиться в диапазоне от 0 до 1.', ...
        imya_polya));
end
end

function znachenie = proverit_konechnoe_chislo(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Параметр %s должен быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
end

function znachenie = proverit_logicheskoe_znachenie(znachenie, imya_polya)
if ~(islogical(znachenie) && isscalar(znachenie))
    error('%s', sprintf( ...
        'Параметр %s должен быть логическим скаляром.', ...
        imya_polya));
end
end
