function rezultat_serii_resursov = raschet_resursov_po_serii(rezultat_serii, parametry_resursov)
if nargin < 2
    error('%s', [ ...
        'Для расчета ресурсов по серии требуются результат серии ' ...
        'и параметры ресурсов.' ...
        ]);
end

parametry_resursov = proverit_parametry_resursov(parametry_resursov);
rezultat_serii = proverit_rezultat_serii(rezultat_serii);

chislo_variantov = numel(rezultat_serii.rezultaty_opytov);
resursy_po_variantam = cell(1, chislo_variantov);
spisok_pokazatelei = cell(1, chislo_variantov);

for nomer_varianta = 1:chislo_variantov
    resursy_po_variantam{nomer_varianta} = raschet_resursov_po_opytu( ...
        rezultat_serii.rezultaty_opytov(nomer_varianta), ...
        parametry_resursov);
    spisok_pokazatelei{nomer_varianta} = izvlech_pokazateli_resursov( ...
        resursy_po_variantam{nomer_varianta});
    spisok_pokazatelei{nomer_varianta}.id_varianta = ...
        rezultat_serii.rezultaty_opytov(nomer_varianta).id_varianta;
    spisok_pokazatelei{nomer_varianta}.id_scenariya = ...
        rezultat_serii.rezultaty_opytov(nomer_varianta).id_scenariya;
end

resursy_po_variantam = [resursy_po_variantam{:}];
spisok_pokazatelei = [spisok_pokazatelei{:}];

tablica_resursov = struct2table(spisok_pokazatelei);
tablica_resursov = movevars(tablica_resursov, ...
    {'id_varianta', 'id_scenariya'}, 'Before', 1);

rezultat_serii_resursov = struct();
rezultat_serii_resursov.id_serii = char(string(rezultat_serii.id_serii));
rezultat_serii_resursov.resursy_po_variantam = resursy_po_variantam;
rezultat_serii_resursov.tablica_resursov = tablica_resursov;
rezultat_serii_resursov.srednii_ostatok_energii_po_variantam = ...
    tablica_resursov.srednii_ostatok_energii.';
rezultat_serii_resursov.maksimalnaya_nagruzka_golovnyh_po_variantam = ...
    tablica_resursov.maksimalnaya_nagruzka_golovnogo_bvs.';
rezultat_serii_resursov.primechanie = [ ...
    'Ресурсная сводка серии рассчитана по уже выполненным вариантам ' ...
    'без параллельных вычислений и без изменения слоев этапов 3–10.' ...
    ];
end

function rezultat_serii = proverit_rezultat_serii(rezultat_serii)
if ~isstruct(rezultat_serii) ...
        || ~isfield(rezultat_serii, 'id_serii') ...
        || ~isfield(rezultat_serii, 'rezultaty_opytov')
    error('%s', ...
        'Результат серии должен содержать идентификатор и список опытов.');
end

if ~isstruct(rezultat_serii.rezultaty_opytov) ...
        || isempty(rezultat_serii.rezultaty_opytov)
    error('%s', ...
        'Список результатов опытов серии должен быть непустым.');
end
end
