function sostoyaniya_resursov = sozdat_sostoyanie_resursov_bvs(scenarii, sostoyaniya_bvs)
if nargin < 2
    error('%s', [ ...
        'Для создания состояния ресурсов БВС требуются структура сценария ' ...
        'и массив состояний БВС.' ...
        ]);
end

if ~isstruct(scenarii) || ~isfield(scenarii, 'sostav_roya') ...
        || ~isfield(scenarii.sostav_roya, 'bvs')
    error('%s', ...
        'Структура сценария должна содержать состав роя с перечнем БВС.');
end

if ~isstruct(sostoyaniya_bvs) || isempty(sostoyaniya_bvs)
    error('%s', ...
        'Состояния БВС для создания состояния ресурсов заданы некорректно.');
end

spisok_bvs_scenariya = scenarii.sostav_roya.bvs;
if numel(spisok_bvs_scenariya) ~= numel(sostoyaniya_bvs)
    error('%s', [ ...
        'Число БВС в состоянии ресурсов не совпадает с составом роя ' ...
        'из сценария.' ...
        ]);
end

sostoyaniya_resursov = repmat(struct( ...
    'id_bvs', '', ...
    'energiya_ostatok_dzh', 0, ...
    'vychislitelnaya_nagruzka', 0, ...
    'nagruzka_svyazi', 0, ...
    'zanyatost_ocheredi', 0, ...
    'chislo_obrabotannyh_soobshchenii', 0, ...
    'chislo_peredannyh_bit', 0, ...
    'yavlyaetsya_golovnym_bvs', false, ...
    'rabotosposoben_po_resursam', true), ...
    1, numel(sostoyaniya_bvs));

for nomer_bvs = 1:numel(sostoyaniya_bvs)
    sostoyanie_bvs = proverit_sostoyanie_bvs(sostoyaniya_bvs(nomer_bvs));
    dannye_scenariya = spisok_bvs_scenariya(nomer_bvs);

    if ~strcmp(char(string(dannye_scenariya.id_bvs)), sostoyanie_bvs.id_bvs)
        error('%s', sprintf( ...
            'Порядок БВС в сценарии и в состоянии не совпадает для %s.', ...
            sostoyanie_bvs.id_bvs));
    end

    energiya = double(sostoyanie_bvs.zapas_energii);
    if ~isscalar(energiya) || ~isfinite(energiya) || energiya < 0
        error('%s', sprintf( ...
            'Начальный запас энергии БВС %s должен быть конечным ' ...
            'неотрицательным числом.', ...
            sostoyanie_bvs.id_bvs));
    end

    sostoyaniya_resursov(nomer_bvs).id_bvs = sostoyanie_bvs.id_bvs;
    sostoyaniya_resursov(nomer_bvs).energiya_ostatok_dzh = energiya;
end
end
