function parametry = parametry_peredachi_po_umolchaniyu()
parametry = struct( ...
    'maksimalnyi_razmer_ocheredi', 6, ...
    'maksimalnoe_chislo_peresylok', 8, ...
    'vremya_zhizni_soobshcheniya_s', 30.0, ...
    'bazovyi_razmer_soobshcheniya_bit', 512.0, ...
    'propuskat_cherez_golovnye_bvs', true, ...
    'razreshit_pryamuyu_peredachu', true, ...
    'shtraf_za_perepolnenie_ocheredi', 1.0, ...
    'ves_zaderzhki', 0.25, ...
    'ves_chisla_peresylok', 0.25, ...
    'ves_dostavki', 0.50);

parametry = proverit_parametry_peredachi(parametry);
end
