function parametry = proverit_parametry_peredachi(parametry)
if nargin < 1 || ~isstruct(parametry)
    error('%s', ...
        'Для проверки параметров передачи требуется структура параметров.');
end

obyazatelnye_polya = {
    'maksimalnyi_razmer_ocheredi'
    'maksimalnoe_chislo_peresylok'
    'vremya_zhizni_soobshcheniya_s'
    'bazovyi_razmer_soobshcheniya_bit'
    'propuskat_cherez_golovnye_bvs'
    'razreshit_pryamuyu_peredachu'
    'shtraf_za_perepolnenie_ocheredi'
    'ves_zaderzhki'
    'ves_chisla_peresylok'
    'ves_dostavki'
    };

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(parametry, imya_polya)
        error('%s', sprintf( ...
            'В параметрах передачи отсутствует обязательное поле %s.', ...
            imya_polya));
    end
end

parametry.maksimalnyi_razmer_ocheredi = proverit_polozhitelnoe_celoe( ...
    parametry.maksimalnyi_razmer_ocheredi, ...
    'maksimalnyi_razmer_ocheredi');
parametry.maksimalnoe_chislo_peresylok = proverit_polozhitelnoe_celoe( ...
    parametry.maksimalnoe_chislo_peresylok, ...
    'maksimalnoe_chislo_peresylok');
parametry.vremya_zhizni_soobshcheniya_s = proverit_polozhitelnoe_chislo( ...
    parametry.vremya_zhizni_soobshcheniya_s, ...
    'vremya_zhizni_soobshcheniya_s');
parametry.bazovyi_razmer_soobshcheniya_bit = proverit_polozhitelnoe_chislo( ...
    parametry.bazovyi_razmer_soobshcheniya_bit, ...
    'bazovyi_razmer_soobshcheniya_bit');
parametry.shtraf_za_perepolnenie_ocheredi = proverit_neotritsatelnoe_chislo( ...
    parametry.shtraf_za_perepolnenie_ocheredi, ...
    'shtraf_za_perepolnenie_ocheredi');
parametry.ves_zaderzhki = proverit_neotritsatelnoe_chislo( ...
    parametry.ves_zaderzhki, ...
    'ves_zaderzhki');
parametry.ves_chisla_peresylok = proverit_neotritsatelnoe_chislo( ...
    parametry.ves_chisla_peresylok, ...
    'ves_chisla_peresylok');
parametry.ves_dostavki = proverit_neotritsatelnoe_chislo( ...
    parametry.ves_dostavki, ...
    'ves_dostavki');

if ~islogical(parametry.propuskat_cherez_golovnye_bvs) ...
        || ~isscalar(parametry.propuskat_cherez_golovnye_bvs)
    error('%s', [ ...
        'Поле propuskat_cherez_golovnye_bvs должно быть логическим скаляром.' ...
        ]);
end

if ~islogical(parametry.razreshit_pryamuyu_peredachu) ...
        || ~isscalar(parametry.razreshit_pryamuyu_peredachu)
    error('%s', [ ...
        'Поле razreshit_pryamuyu_peredachu должно быть логическим скаляром.' ...
        ]);
end

summa_vesov = ...
    parametry.ves_zaderzhki ...
    + parametry.ves_chisla_peresylok ...
    + parametry.ves_dostavki;
if summa_vesov <= 0
    error('%s', ...
        'Сумма весов качества передачи должна быть положительной.');
end
end

function znachenie = proverit_polozhitelnoe_celoe(znachenie, imya_polya)
znachenie = proverit_polozhitelnoe_chislo(znachenie, imya_polya);
if abs(znachenie - round(znachenie)) > eps(max(1, abs(znachenie)))
    error('%s', sprintf( ...
        'Поле %s должно быть целым числом.', ...
        imya_polya));
end
znachenie = double(round(znachenie));
end

function znachenie = proverit_polozhitelnoe_chislo(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie <= 0
    error('%s', sprintf( ...
        'Поле %s должно быть положительным.', ...
        imya_polya));
end
end

function znachenie = proverit_neotritsatelnoe_chislo(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie < 0
    error('%s', sprintf( ...
        'Поле %s не должно быть отрицательным.', ...
        imya_polya));
end
end
