function [obnovlennye_ocheredi, zhurnal_sobytii] = vypolnit_shag_peredachi(ocheredi_bvs, graf_svyaznosti, sostoyaniya_bvs, dannye_zvenev, tekushchee_vremya, parametry_peredachi)
if nargin < 6
    error('%s', [ ...
        'Для выполнения шага передачи требуются очереди БВС, граф связности, ' ...
        'состояния БВС, данные звеньев, время и параметры передачи.' ...
        ]);
end

parametry_peredachi = proverit_parametry_peredachi(parametry_peredachi);
[ocheredi_bvs, identifikatory_bvs] = proverit_ocheredi(ocheredi_bvs);
sostoyaniya_bvs = proverit_sostoyaniya(sostoyaniya_bvs, identifikatory_bvs);
graf_svyaznosti = proverit_graf(graf_svyaznosti, identifikatory_bvs);
proverit_dannye_zvenev(dannye_zvenev);

if ~isnumeric(tekushchee_vremya) || ~isscalar(tekushchee_vremya) ...
        || ~isfinite(tekushchee_vremya)
    error('%s', ...
        'Текущее время шага передачи должно быть конечным числом.');
end

obnovlennye_ocheredi = sozdat_ocheredi_bvs( ...
    identifikatory_bvs, ...
    struct([]), ...
    parametry_peredachi);
zhurnal_sobytii = struct([]);

for nomer_ocheredi = 1:numel(ocheredi_bvs)
    spisok_soobshchenii = ocheredi_bvs(nomer_ocheredi).soobshcheniya;

    for nomer_soobshcheniya = 1:numel(spisok_soobshchenii)
        soobshchenie = proverit_soobshchenie(spisok_soobshchenii{nomer_soobshcheniya});
        [obnovlennye_ocheredi, sobytie] = obrabotat_soobshchenie( ...
            obnovlennye_ocheredi, ...
            soobshchenie, ...
            graf_svyaznosti, ...
            sostoyaniya_bvs, ...
            dannye_zvenev, ...
            double(tekushchee_vremya), ...
            parametry_peredachi);
        zhurnal_sobytii = dobavit_sobytie(zhurnal_sobytii, sobytie);
    end
end
end

function [obnovlennye_ocheredi, sobytie] = obrabotat_soobshchenie(obnovlennye_ocheredi, soobshchenie, graf, sostoyaniya, dannye_zvenev, vremya, parametry_peredachi)
if soobshchenie.dostavleno || soobshchenie.poteryano
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'ozhidaet', ...
        soobshchenie, ...
        soobshchenie.tekushchii_bvs, ...
        '', ...
        'Сообщение уже имеет конечное состояние и не должно находиться в очереди.');
    return
end

if vremya - soobshchenie.vremya_sozdaniya > ...
        parametry_peredachi.vremya_zhizni_soobshcheniya_s
    soobshchenie.poteryano = true;
    soobshchenie.prichina_poteri = 'vremya_zhizni_isteklo';
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'poteryano_po_vremeni_zhizni', ...
        soobshchenie, ...
        soobshchenie.tekushchii_bvs, ...
        '', ...
        'Сообщение потеряно по времени жизни.');
    return
end

if strcmp(soobshchenie.tekushchii_bvs, soobshchenie.id_poluchatelya)
    soobshchenie.dostavleno = true;
    soobshchenie.vremya_dostavki = vremya;
    soobshchenie.zaderzhka_dostavki_s = ...
        vremya - soobshchenie.vremya_sozdaniya;
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'dostavleno', ...
        soobshchenie, ...
        soobshchenie.tekushchii_bvs, ...
        soobshchenie.id_poluchatelya, ...
        'Сообщение уже находится у получателя.');
    return
end

if soobshchenie.chislo_peresylok >= ...
        parametry_peredachi.maksimalnoe_chislo_peresylok
    soobshchenie.poteryano = true;
    soobshchenie.prichina_poteri = 'prevysheno_chislo_peresylok';
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'poteryano_po_chislu_peresylok', ...
        soobshchenie, ...
        soobshchenie.tekushchii_bvs, ...
        '', ...
        'Сообщение потеряно по ограничению числа пересылок.');
    return
end

[id_sleduyushchego_bvs, prichina_vybora] = vybrat_sleduyushchii_bvs( ...
    soobshchenie, ...
    graf, ...
    sostoyaniya, ...
    dannye_zvenev, ...
    parametry_peredachi);

if isempty(id_sleduyushchego_bvs)
    [obnovlennye_ocheredi, soobshchenie, dobavleno] = ...
        dobavit_soobshchenie_v_ochered( ...
        obnovlennye_ocheredi, ...
        soobshchenie.tekushchii_bvs, ...
        soobshchenie, ...
        parametry_peredachi);

    if dobavleno
        sobytie = sozdat_sobytie( ...
            vremya, ...
            'ozhidaet', ...
            soobshchenie, ...
            soobshchenie.tekushchii_bvs, ...
            '', ...
            prichina_vybora);
    else
        sobytie = sozdat_sobytie( ...
            vremya, ...
            'poteryano_iz_za_perepolneniya_ocheredi', ...
            soobshchenie, ...
            soobshchenie.tekushchii_bvs, ...
            '', ...
            'Сообщение потеряно из-за переполнения очереди.');
    end
    return
end

[indeks_tekushchego, indeks_sleduyushchego] = nayti_indeksy_linii( ...
    graf.id_bvs, ...
    soobshchenie.tekushchii_bvs, ...
    id_sleduyushchego_bvs);
propusknaya_sposobnost = ...
    graf.matrica_propusknoy_sposobnosti_bit_s( ...
    indeks_tekushchego, ...
    indeks_sleduyushchego);

if propusknaya_sposobnost + 1e-9 < soobshchenie.razmer_bit
    [obnovlennye_ocheredi, soobshchenie, dobavleno] = ...
        dobavit_soobshchenie_v_ochered( ...
        obnovlennye_ocheredi, ...
        soobshchenie.tekushchii_bvs, ...
        soobshchenie, ...
        parametry_peredachi);

    if dobavleno
        sobytie = sozdat_sobytie( ...
            vremya, ...
            'ozhidaet', ...
            soobshchenie, ...
            soobshchenie.tekushchii_bvs, ...
            '', ...
            'Пропускной способности линии недостаточно для передачи сообщения за текущий шаг.');
    else
        sobytie = sozdat_sobytie( ...
            vremya, ...
            'poteryano_iz_za_perepolneniya_ocheredi', ...
            soobshchenie, ...
            soobshchenie.tekushchii_bvs, ...
            '', ...
            'Сообщение потеряно из-за переполнения очереди.');
    end
    return
end

soobshchenie.tekushchii_bvs = id_sleduyushchego_bvs;
soobshchenie.marshrut{end + 1} = id_sleduyushchego_bvs;
soobshchenie.chislo_peresylok = soobshchenie.chislo_peresylok + 1;

if strcmp(id_sleduyushchego_bvs, soobshchenie.id_poluchatelya)
    soobshchenie.dostavleno = true;
    soobshchenie.vremya_dostavki = vremya;
    soobshchenie.zaderzhka_dostavki_s = ...
        vremya - soobshchenie.vremya_sozdaniya;
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'dostavleno', ...
        soobshchenie, ...
        graf.id_bvs{indeks_tekushchego}, ...
        id_sleduyushchego_bvs, ...
        prichina_vybora);
    return
end

[obnovlennye_ocheredi, soobshchenie, dobavleno] = dobavit_soobshchenie_v_ochered( ...
    obnovlennye_ocheredi, ...
    id_sleduyushchego_bvs, ...
    soobshchenie, ...
    parametry_peredachi);

if dobavleno
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'peredano', ...
        soobshchenie, ...
        graf.id_bvs{indeks_tekushchego}, ...
        id_sleduyushchego_bvs, ...
        prichina_vybora);
else
    sobytie = sozdat_sobytie( ...
        vremya, ...
        'poteryano_iz_za_perepolneniya_ocheredi', ...
        soobshchenie, ...
        graf.id_bvs{indeks_tekushchego}, ...
        id_sleduyushchego_bvs, ...
        'Сообщение потеряно из-за переполнения очереди.');
end
end

function sobytie = sozdat_sobytie(tekushchee_vremya, tip_sobytiya, soobshchenie, id_tekushchego_bvs, id_sleduyushchego_bvs, prichina)
sobytie = struct();
sobytie.vremya_sobytiya = double(tekushchee_vremya);
sobytie.tip_sobytiya = char(string(tip_sobytiya));
sobytie.id_soobshcheniya = char(string(soobshchenie.id_soobshcheniya));
sobytie.id_tekushchego_bvs = char(string(id_tekushchego_bvs));
sobytie.id_sleduyushchego_bvs = char(string(id_sleduyushchego_bvs));
sobytie.prichina = char(string(prichina));
sobytie.soobshchenie = soobshchenie;
end

function zhurnal_sobytii = dobavit_sobytie(zhurnal_sobytii, sobytie)
if isempty(zhurnal_sobytii)
    zhurnal_sobytii = sobytie;
else
    zhurnal_sobytii(end + 1) = sobytie; %#ok<AGROW>
end
end

function [ocheredi_bvs, identifikatory_bvs] = proverit_ocheredi(ocheredi_bvs)
if ~isstruct(ocheredi_bvs) || isempty(ocheredi_bvs)
    error('%s', ...
        'Очереди БВС должны быть заданы непустым массивом структур.');
end

identifikatory_bvs = cell(1, numel(ocheredi_bvs));
for nomer_ocheredi = 1:numel(ocheredi_bvs)
    if ~isfield(ocheredi_bvs(nomer_ocheredi), 'id_bvs') ...
            || ~isfield(ocheredi_bvs(nomer_ocheredi), 'soobshcheniya')
        error('%s', ...
            'Каждая очередь БВС должна содержать поля id_bvs и soobshcheniya.');
    end
    identifikatory_bvs{nomer_ocheredi} = char(string( ...
        ocheredi_bvs(nomer_ocheredi).id_bvs));
end

if numel(unique(identifikatory_bvs)) ~= numel(identifikatory_bvs)
    error('%s', ...
        'Идентификаторы очередей БВС должны быть уникальными.');
end
end

function sostoyaniya_bvs = proverit_sostoyaniya(sostoyaniya_bvs, identifikatory_bvs)
if ~isstruct(sostoyaniya_bvs) || numel(sostoyaniya_bvs) ~= numel(identifikatory_bvs)
    error('%s', ...
        'Состояния БВС для шага передачи заданы некорректно.');
end

for nomer_bvs = 1:numel(sostoyaniya_bvs)
    sostoyaniya_bvs(nomer_bvs) = proverit_sostoyanie_bvs( ...
        sostoyaniya_bvs(nomer_bvs));
end
end

function graf_svyaznosti = proverit_graf(graf_svyaznosti, identifikatory_bvs)
if ~isstruct(graf_svyaznosti) ...
        || ~isfield(graf_svyaznosti, 'id_bvs') ...
        || ~isfield(graf_svyaznosti, 'matrica_propusknoy_sposobnosti_bit_s')
    error('%s', ...
        'Граф связности для шага передачи задан некорректно.');
end

id_bvs = normalizovat_id_bvs(graf_svyaznosti.id_bvs);
if ~isempty(setxor(id_bvs, identifikatory_bvs))
    error('%s', ...
        'Состав графа связности не совпадает с очередями БВС.');
end
end

function proverit_dannye_zvenev(dannye_zvenev)
if ~isstruct(dannye_zvenev) ...
        || ~isfield(dannye_zvenev, 'zvenya') ...
        || ~isfield(dannye_zvenev, 'golovnye_bvs')
    error('%s', ...
        'Данные звеньев для шага передачи заданы некорректно.');
end
end

function soobshchenie = proverit_soobshchenie(soobshchenie)
obyazatelnye_polya = {
    'id_soobshcheniya'
    'id_otpravitelya'
    'id_poluchatelya'
    'tekushchii_bvs'
    'vremya_sozdaniya'
    'razmer_bit'
    'tip_soobshcheniya'
    'marshrut'
    'chislo_peresylok'
    'dostavleno'
    'poteryano'
    'prichina_poteri'
    };

if ~isstruct(soobshchenie)
    error('%s', ...
        'Сообщение в очереди должно быть структурой.');
end

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(soobshchenie, imya_polya)
        error('%s', sprintf( ...
            'В сообщении очереди отсутствует поле %s.', ...
            imya_polya));
    end
end
end

function [indeks_tekushchego, indeks_sleduyushchego] = nayti_indeksy_linii(id_bvs, id_tekushchego_bvs, id_sleduyushchego_bvs)
indeks_tekushchego = find(strcmp(id_bvs, id_tekushchego_bvs), 1);
indeks_sleduyushchego = find(strcmp(id_bvs, id_sleduyushchego_bvs), 1);

if isempty(indeks_tekushchego) || isempty(indeks_sleduyushchego)
    error('%s', ...
        'Не удалось сопоставить линию передачи с индексами БВС.');
end
end

function id_bvs = normalizovat_id_bvs(id_bvs)
if isstring(id_bvs)
    id_bvs = cellstr(id_bvs(:).');
elseif ischar(id_bvs)
    id_bvs = {id_bvs};
end

id_bvs = cellfun(@(znachenie) char(string(znachenie)), ...
    id_bvs, ...
    'UniformOutput', false);
end
