function parametry = parametry_zvenev_po_umolchaniyu()
parametry = struct( ...
    'minimalnyi_razmer_zvena', 1, ...
    'maksimalnyi_razmer_zvena', 3, ...
    'ves_stepeni_bvs', 0.35, ...
    'ves_poleznosti_linii', 0.30, ...
    'ves_centralnosti', 0.20, ...
    'ves_zapasa_energii', 0.15, ...
    'razreshit_odinochnye_zvenya', true);

parametry = proverit_parametry_zvenev(parametry);
end
