function parametry = proverit_parametry_zvenev(parametry)
if nargin < 1 || ~isstruct(parametry)
    error('%s', ...
        'Для проверки параметров звеньев требуется структура параметров.');
end

obyazatelnye_polya = {
    'minimalnyi_razmer_zvena'
    'maksimalnyi_razmer_zvena'
    'ves_stepeni_bvs'
    'ves_poleznosti_linii'
    'ves_centralnosti'
    'ves_zapasa_energii'
    'razreshit_odinochnye_zvenya'
    };

for nomer_polya = 1:numel(obyazatelnye_polya)
    imya_polya = obyazatelnye_polya{nomer_polya};
    if ~isfield(parametry, imya_polya)
        error('%s', sprintf( ...
            'В параметрах звеньев отсутствует обязательное поле %s.', ...
            imya_polya));
    end
end

parametry.minimalnyi_razmer_zvena = proverit_celoe_polozhitelnoe( ...
    parametry.minimalnyi_razmer_zvena, ...
    'minimalnyi_razmer_zvena');
parametry.maksimalnyi_razmer_zvena = proverit_celoe_polozhitelnoe( ...
    parametry.maksimalnyi_razmer_zvena, ...
    'maksimalnyi_razmer_zvena');
parametry.ves_stepeni_bvs = proverit_neotricatelnoe( ...
    parametry.ves_stepeni_bvs, ...
    'ves_stepeni_bvs');
parametry.ves_poleznosti_linii = proverit_neotricatelnoe( ...
    parametry.ves_poleznosti_linii, ...
    'ves_poleznosti_linii');
parametry.ves_centralnosti = proverit_neotricatelnoe( ...
    parametry.ves_centralnosti, ...
    'ves_centralnosti');
parametry.ves_zapasa_energii = proverit_neotricatelnoe( ...
    parametry.ves_zapasa_energii, ...
    'ves_zapasa_energii');
parametry.razreshit_odinochnye_zvenya = proverit_logicheskoe( ...
    parametry.razreshit_odinochnye_zvenya, ...
    'razreshit_odinochnye_zvenya');

if parametry.maksimalnyi_razmer_zvena < parametry.minimalnyi_razmer_zvena
    error('%s', [ ...
        'Максимальный размер звена должен быть больше или равен ' ...
        'минимальному размеру звена.' ...
        ]);
end

summa_vesov = parametry.ves_stepeni_bvs ...
    + parametry.ves_poleznosti_linii ...
    + parametry.ves_centralnosti ...
    + parametry.ves_zapasa_energii;
if summa_vesov <= 0
    error('%s', [ ...
        'Сумма весов выбора головного БВС должна быть положительной.' ...
        ]);
end
end

function znachenie = proverit_celoe_polozhitelnoe(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie < 1 || abs(znachenie - round(znachenie)) > eps(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть целым числом не меньше 1.', ...
        imya_polya));
end

znachenie = round(znachenie);
end

function znachenie = proverit_neotricatelnoe(znachenie, imya_polya)
if ~isnumeric(znachenie) || ~isscalar(znachenie) || ~isfinite(znachenie)
    error('%s', sprintf( ...
        'Поле %s должно быть конечным числом.', ...
        imya_polya));
end

znachenie = double(znachenie);
if znachenie < 0
    error('%s', sprintf( ...
        'Поле %s не может быть отрицательным.', ...
        imya_polya));
end
end

function znachenie = proverit_logicheskoe(znachenie, imya_polya)
if ~(islogical(znachenie) && isscalar(znachenie)) ...
        && ~(isnumeric(znachenie) && isscalar(znachenie))
    error('%s', sprintf( ...
        'Поле %s должно быть логическим признаком.', ...
        imya_polya));
end

znachenie = logical(znachenie);
end
