function varianty = sozdat_varianty_serii_opytov(plan_ili_struktura)
if ischar(plan_ili_struktura) || isstring(plan_ili_struktura)
    plan_serii = zagruzit_plan_serii_opytov(char(string(plan_ili_struktura)));
else
    plan_serii = proverit_plan_serii_opytov(plan_ili_struktura);
end

varianty = repmat(struct( ...
    'id_serii', '', ...
    'id_varianta', '', ...
    'id_scenariya', '', ...
    'nomer_povtora', 0, ...
    'parametry_svyazi', struct(), ...
    'parametry_zvenev', struct(), ...
    'parametry_peredachi', struct(), ...
    'primechanie', ''), 1, 0);

schetchik = 0;
for nomer_scenariya = 1:numel(plan_serii.spisok_scenariev)
    for nomer_povtora = 1:plan_serii.chislo_povtorov
        for nomer_svyazi = 1:numel(plan_serii.varianty_parametrov_svyazi)
            for nomer_zvenev = 1:numel(plan_serii.varianty_parametrov_zvenev)
                for nomer_peredachi = 1:numel(plan_serii.varianty_parametrov_peredachi)
                    schetchik = schetchik + 1;
                    variant = struct();
                    variant.id_serii = plan_serii.id_serii;
                    variant.id_varianta = sprintf('%s_v%02d', ...
                        plan_serii.id_serii, schetchik);
                    variant.id_scenariya = ...
                        plan_serii.spisok_scenariev{nomer_scenariya};
                    variant.nomer_povtora = nomer_povtora;
                    variant.parametry_svyazi = ...
                        plan_serii.varianty_parametrov_svyazi(nomer_svyazi);
                    variant.parametry_zvenev = ...
                        plan_serii.varianty_parametrov_zvenev(nomer_zvenev);
                    variant.parametry_peredachi = ...
                        plan_serii.varianty_parametrov_peredachi(nomer_peredachi);
                    variant.primechanie = sprintf([ ...
                        'Сценарий %s, повтор %d, наборы связи %d, звеньев %d ' ...
                        'и передачи %d.' ...
                        ], ...
                        variant.id_scenariya, ...
                        variant.nomer_povtora, ...
                        nomer_svyazi, ...
                        nomer_zvenev, ...
                        nomer_peredachi);
                    varianty(1, schetchik) = variant; %#ok<AGROW>
                end
            end
        end
    end
end

limit = plan_serii.ogranichenie_malogo_rezhima_proverki;
if limit > 0 && numel(varianty) > limit
    varianty = varianty(1:limit);
end

if isempty(varianty)
    error('%s', 'План серии не породил ни одного варианта опыта.');
end
end
