function rezultat_serii = vypolnit_seriyu_opytov(koren_proekta, plan_ili_put)
if nargin < 2
    error('%s', ...
        'Для выполнения серии требуются корень проекта и план серии.');
end

if isstruct(plan_ili_put)
    plan_serii = proverit_plan_serii_opytov(plan_ili_put);
else
    plan_serii = zagruzit_plan_serii_opytov(plan_ili_put);
end

varianty = sozdat_varianty_serii_opytov(plan_serii);
rezultaty_opytov = repmat(struct( ...
    'id_serii', '', ...
    'id_varianta', '', ...
    'id_scenariya', '', ...
    'nomer_povtora', 0, ...
    'scenarii', struct(), ...
    'parametry_svyazi', struct(), ...
    'parametry_zvenev', struct(), ...
    'parametry_peredachi', struct(), ...
    'kinematika', struct(), ...
    'svyaznost', struct(), ...
    'zvenya', struct(), ...
    'peredacha', struct(), ...
    'vremya_vypolneniya_s', 0, ...
    'primechanie', '', ...
    'pokazateli', struct()), 1, numel(varianty));

soobshchenie(sprintf( ...
    'Запуск серии %s. Число вариантов: %d.', ...
    plan_serii.id_serii, ...
    numel(varianty)));

for nomer_varianta = 1:numel(varianty)
    soobshchenie(sprintf( ...
        'Выполняется вариант %d из %d: %s.', ...
        nomer_varianta, ...
        numel(varianty), ...
        varianty(nomer_varianta).id_varianta));
    rezultaty_opytov(nomer_varianta) = vypolnit_odin_opyt( ...
        koren_proekta, ...
        varianty(nomer_varianta));
end

tablica_sravneniya = sravnit_rezultaty_serii(rezultaty_opytov);

rezultat_serii = struct();
rezultat_serii.id_serii = plan_serii.id_serii;
rezultat_serii.plan_serii = plan_serii;
rezultat_serii.varianty = varianty;
rezultat_serii.rezultaty_opytov = rezultaty_opytov;
rezultat_serii.tablica_sravneniya = tablica_sravneniya;
rezultat_serii.papka_rezultatov = '';
rezultat_serii.puti_k_grafikam = {};
rezultat_serii.primechanie = [ ...
    'Серия опытов выполнена последовательно без параллельных вычислений ' ...
    'и без открытия видимых окон.' ...
    ];

if plan_serii.sohranyat_otchet || plan_serii.sohranyat_grafiki
    rezultat_serii.papka_rezultatov = sohranit_rezultaty_serii( ...
        koren_proekta, ...
        rezultat_serii);
end

if plan_serii.sohranyat_grafiki
    grafiki = postroit_grafiki_serii_opytov( ...
        rezultat_serii, ...
        false, ...
        rezultat_serii.papka_rezultatov);
    rezultat_serii.puti_k_grafikam = grafiki.puti_k_failam;
    zakryt_figury(grafiki.figury);
end

soobshchenie(sprintf( ...
    'Серия %s завершена успешно.', ...
    plan_serii.id_serii));
end

function zakryt_figury(figury)
for nomer_figury = 1:numel(figury)
    if isgraphics(figury(nomer_figury))
        close(figury(nomer_figury));
    end
end
end
