function rezultat_peredachi = proverka_peredachi_etapa_6(koren_proekta)
put_k_scenariyu = fullfile( ...
    koren_proekta, 'opyty', 'scenarii', 'bazovye', 'stroi_malyi.json');

if ~isfile(put_k_scenariyu)
    error('%s', sprintf( ...
        'Не найден сценарий для проверки передачи этапа 6: %s', ...
        put_k_scenariyu));
end

scenarii = zagruzit_scenarii(put_k_scenariyu);
rezultat_kinematiki = raschet_passivnoi_kinematiki(scenarii);
parametry_svyazi = parametry_svyazi_po_umolchaniyu();
rezultat_svyaznosti = raschet_svyaznosti_po_kinematike( ...
    rezultat_kinematiki, ...
    parametry_svyazi);
parametry_zvenev = parametry_zvenev_po_umolchaniyu();
rezultat_zvenev = raschet_zvenev_po_svyaznosti( ...
    rezultat_svyaznosti, ...
    parametry_zvenev);
parametry_peredachi = parametry_peredachi_po_umolchaniyu();
nachalnye_soobshcheniya = sozdat_nachalnye_soobshcheniya( ...
    scenarii, ...
    parametry_peredachi);
rezultat_peredachi = raschet_peredachi_po_trasse( ...
    scenarii, ...
    rezultat_kinematiki, ...
    rezultat_svyaznosti, ...
    rezultat_zvenev, ...
    parametry_peredachi);

proverit_chislo_soobshchenii(nachalnye_soobshcheniya, rezultat_peredachi);
proverit_marshruty(rezultat_peredachi.soobshcheniya);
proverit_zaderzhki_dostavki(rezultat_peredachi.soobshcheniya);
proverit_dolyu_dostavlennyh(rezultat_peredachi);
proverit_ogranichenie_na_peresylki(rezultat_peredachi, parametry_peredachi);
proverit_povtornyi_raschet( ...
    scenarii, ...
    rezultat_kinematiki, ...
    rezultat_svyaznosti, ...
    rezultat_zvenev, ...
    parametry_peredachi, ...
    rezultat_peredachi);
proverit_rezhim_s_odnoi_peresylkoi( ...
    scenarii, ...
    rezultat_kinematiki, ...
    rezultat_svyaznosti, ...
    rezultat_zvenev, ...
    parametry_peredachi, ...
    rezultat_peredachi);

soobshchenie('Передача сообщений этапа 6 проверена успешно');
end

function proverit_chislo_soobshchenii(nachalnye_soobshcheniya, rezultat_peredachi)
if numel(nachalnye_soobshcheniya) < 3 || rezultat_peredachi.chislo_soobshchenii < 3
    error('%s', ...
        'На этапе 6 требуется не менее трех модельных сообщений.');
end
end

function proverit_marshruty(soobshcheniya)
for nomer_soobshcheniya = 1:numel(soobshcheniya)
    tekushchee_soobshchenie = soobshcheniya(nomer_soobshcheniya);

    if strlength(string(tekushchee_soobshchenie.id_otpravitelya)) == 0 ...
            || strlength(string(tekushchee_soobshchenie.id_poluchatelya)) == 0
        error('%s', sprintf( ...
            'Сообщение %s не содержит отправителя или получателя.', ...
            tekushchee_soobshchenie.id_soobshcheniya));
    end

    if ~iscell(tekushchee_soobshchenie.marshrut) ...
            || isempty(tekushchee_soobshchenie.marshrut)
        error('%s', sprintf( ...
            'Сообщение %s не содержит маршрут.', ...
            tekushchee_soobshchenie.id_soobshcheniya));
    end
end
end

function proverit_zaderzhki_dostavki(soobshcheniya)
dostavlennye_soobshcheniya = soobshcheniya([soobshcheniya.dostavleno]);
for nomer_soobshcheniya = 1:numel(dostavlennye_soobshcheniya)
    tekushchee_soobshchenie = dostavlennye_soobshcheniya(nomer_soobshcheniya);
    if ~isfinite(tekushchee_soobshchenie.zaderzhka_dostavki_s)
        error('%s', sprintf( ...
            'Доставленное сообщение %s должно иметь конечную задержку.', ...
            tekushchee_soobshchenie.id_soobshcheniya));
    end
end
end

function proverit_dolyu_dostavlennyh(rezultat_peredachi)
if rezultat_peredachi.dolya_dostavlennyh < 0 ...
        || rezultat_peredachi.dolya_dostavlennyh > 1
    error('%s', ...
        'Доля доставленных сообщений должна находиться в диапазоне от 0 до 1.');
end
end

function proverit_ogranichenie_na_peresylki(rezultat_peredachi, parametry_peredachi)
chisla_peresylok = [rezultat_peredachi.soobshcheniya.chislo_peresylok];
if any(chisla_peresylok > parametry_peredachi.maksimalnoe_chislo_peresylok)
    error('%s', ...
        'Число пересылок сообщения превысило допустимое ограничение.');
end
end

function proverit_povtornyi_raschet(scenarii, rezultat_kinematiki, rezultat_svyaznosti, rezultat_zvenev, parametry_peredachi, etalonnyi_rezultat)
povtornyi_rezultat = raschet_peredachi_po_trasse( ...
    scenarii, ...
    rezultat_kinematiki, ...
    rezultat_svyaznosti, ...
    rezultat_zvenev, ...
    parametry_peredachi);

if ~isequaln(etalonnyi_rezultat, povtornyi_rezultat)
    error('%s', ...
        'Повторный расчет передачи сообщений дал другой результат.');
end
end

function proverit_rezhim_s_odnoi_peresylkoi(scenarii, rezultat_kinematiki, rezultat_svyaznosti, rezultat_zvenev, parametry_peredachi, etalonnyi_rezultat)
parametry_odnogo_shaga = parametry_peredachi;
parametry_odnogo_shaga.maksimalnoe_chislo_peresylok = 1;
parametry_odnogo_shaga = proverit_parametry_peredachi(parametry_odnogo_shaga);

rezultat_odnogo_shaga = raschet_peredachi_po_trasse( ...
    scenarii, ...
    rezultat_kinematiki, ...
    rezultat_svyaznosti, ...
    rezultat_zvenev, ...
    parametry_odnogo_shaga);

if rezultat_odnogo_shaga.chislo_dostavlennyh > etalonnyi_rezultat.chislo_dostavlennyh
    error('%s', [ ...
        'При ограничении числа пересылок до одного число доставленных сообщений ' ...
        'не должно увеличиваться.' ...
        ]);
end
end
