function [parametry_svyazi, parametry_zvenev, parametry_peredachi] = poluchit_parametry_iz_pulta(pult)
if nargin < 1 || ~isstruct(pult) || ~isfield(pult, 'elementy')
    error('%s', 'Для чтения параметров требуется структура пульта.');
end

svyaz = pult.elementy.svyaz;
parametry_svyazi = struct( ...
    'moshchnost_peredatchika_vt', double(svyaz.moshchnost_peredatchika.Value), ...
    'usilenie_kanala', 1.0, ...
    'pokazatel_poter', 2.2, ...
    'moshchnost_shuma_vt', double(svyaz.moshchnost_shuma.Value), ...
    'polosa_chastot_gts', double(svyaz.polosa_chastot.Value), ...
    'porog_otnosheniya_signal_shum', double(svyaz.porog_signal_shum.Value), ...
    'minimalnaya_dalnost_m', 1.0, ...
    'maksimalnaya_dalnost_m', double(svyaz.maksimalnaya_dalnost.Value), ...
    'razmer_soobshcheniya_bit', double(svyaz.razmer_soobshcheniya.Value), ...
    'ves_propusknoi_sposobnosti', double(svyaz.ves_propusknoi_sposobnosti.Value), ...
    'ves_dlitelnosti_svyazi', double(svyaz.ves_dlitelnosti_svyazi.Value), ...
    'ves_energeticheskoi_stoimosti', double(svyaz.ves_energeticheskoi_stoimosti.Value));

zvenya = pult.elementy.zvenya;
parametry_zvenev = struct( ...
    'minimalnyi_razmer_zvena', double(zvenya.minimalnyi_razmer_zvena.Value), ...
    'maksimalnyi_razmer_zvena', double(zvenya.maksimalnyi_razmer_zvena.Value), ...
    'ves_stepeni_bvs', double(zvenya.ves_stepeni_bvs.Value), ...
    'ves_poleznosti_linii', double(zvenya.ves_poleznosti_linii.Value), ...
    'ves_centralnosti', double(zvenya.ves_centralnosti.Value), ...
    'ves_zapasa_energii', double(zvenya.ves_zapasa_energii.Value), ...
    'razreshit_odinochnye_zvenya', logical(zvenya.razreshit_odinochnye_zvenya.Value));

peredacha = pult.elementy.peredacha;
parametry_peredachi = struct( ...
    'maksimalnyi_razmer_ocheredi', double(peredacha.maksimalnyi_razmer_ocheredi.Value), ...
    'maksimalnoe_chislo_peresylok', double(peredacha.maksimalnoe_chislo_peresylok.Value), ...
    'vremya_zhizni_soobshcheniya_s', double(peredacha.vremya_zhizni_soobshcheniya.Value), ...
    'bazovyi_razmer_soobshcheniya_bit', double(peredacha.bazovyi_razmer_soobshcheniya.Value), ...
    'propuskat_cherez_golovnye_bvs', logical(peredacha.propuskat_cherez_golovnye_bvs.Value), ...
    'razreshit_pryamuyu_peredachu', logical(peredacha.razreshit_pryamuyu_peredachu.Value), ...
    'shtraf_za_perepolnenie_ocheredi', 1.0, ...
    'ves_zaderzhki', double(peredacha.ves_zaderzhki.Value), ...
    'ves_chisla_peresylok', double(peredacha.ves_chisla_peresylok.Value), ...
    'ves_dostavki', double(peredacha.ves_dostavki.Value));

[parametry_svyazi, parametry_zvenev, parametry_peredachi] = ...
    proverit_parametry_pulta( ...
    parametry_svyazi, ...
    parametry_zvenev, ...
    parametry_peredachi);
end
