function [put_k_modeli, imya_modeli] = otkryt_model_stenda_roya(koren_proekta)
if nargin < 1 || strlength(string(koren_proekta)) == 0
    koren_proekta = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end

imya_modeli = 'SWARM_MIL_STEND';
put_k_modeli = fullfile( ...
    koren_proekta, ...
    'bloki', ...
    'generated', ...
    [imya_modeli '.slx']);

if ~isfile(put_k_modeli)
    [put_k_modeli, imya_modeli] = sozdat_model_stenda_roya( ...
        koren_proekta, ...
        true, ...
        true);
else
    open_system(put_k_modeli);
end

soobshchenie(sprintf( ...
    'Открыта модель Simulink-стенда: %s', ...
    put_k_modeli));
end
